export const PRINCIPAL_COLOR = "#696ceb"
export const GREEN_COLOR = "#4CAF50"
export const SELECTED_COLOR_OPTION = "#696beb40"
export const RED_DELETE = "#FF4D4F"
export const BLUE_COLOR = "#2196F3"
export const ORANGE_COLOR = "#FFA726"